from typing import Dict, List

from ..models.feedback import FeedbackItem
from ..models.scores import CategoryScores, CoachingScores


SEVERITY_PRIORITY = {
    "high": 4,
    "medium": 3,
    "low": 2,
    "positive": 1,
}


def aggregate_feedback(
    feedback: List[FeedbackItem],
) -> List[FeedbackItem]:
    """
    Combine feedback from all coaching modules.

    The aggregator:
        - removes exact duplicate feedback
        - prioritizes important issues
        - keeps positive feedback
        - returns feedback ordered by severity

    Args:
        feedback:
            Feedback generated by the coaching modules.

    Returns:
        A cleaned and prioritized list of FeedbackItem objects.
    """

    unique_feedback: List[FeedbackItem] = []
    seen = set()

    for item in feedback:
        key = (
            item.category,
            item.title,
            item.issue,
        )

        if key in seen:
            continue

        seen.add(key)
        unique_feedback.append(item)

    unique_feedback.sort(
        key=lambda item: SEVERITY_PRIORITY.get(
            item.severity,
            0,
        ),
        reverse=True,
    )

    return unique_feedback


def calculate_category_scores(
    feedback: List[FeedbackItem],
) -> CategoryScores:
    """
    Calculate category scores from feedback.

    Scores are currently based on the severity of generated
    feedback items.

    This is intentionally simple for now. The scoring formula
    can be refined after evaluating real debate sessions.

    Returns:
        CategoryScores containing scores from 0 to 100.
    """

    categories = {
        "quantitative": [],
        "argumentation": [],
        "rebuttal": [],
        "structure": [],
        "persuasion": [],
        "logic": [],
    }

    for item in feedback:
        if item.category in categories:
            categories[item.category].append(item)

    scores: Dict[str, float] = {}

    for category, items in categories.items():

        if not items:
            scores[category] = 0.0
            continue

        positive = sum(
            1
            for item in items
            if item.severity == "positive"
        )

        high = sum(
            1
            for item in items
            if item.severity == "high"
        )

        medium = sum(
            1
            for item in items
            if item.severity == "medium"
        )

        low = sum(
            1
            for item in items
            if item.severity == "low"
        )

        total = len(items)

        # Simple initial scoring model.
        #
        # Positive feedback improves the score.
        # High severity issues have the largest penalty.
        # Medium and low issues have smaller penalties.
        #
        # This formula is intentionally provisional.

        score = (
            50
            + (positive * 15)
            - (high * 20)
            - (medium * 10)
            - (low * 5)
        )

        score = max(0.0, min(100.0, score))

        scores[category] = round(score, 2)

    return CategoryScores(
        quantitative=scores["quantitative"],
        argumentation=scores["argumentation"],
        rebuttal=scores["rebuttal"],
        structure=scores["structure"],
        persuasion=scores["persuasion"],
        logic=scores["logic"],
    )


def calculate_overall_score(
    category_scores: CategoryScores,
) -> float:
    """
    Calculate the overall coaching score.

    No final weighting has been established yet, so the initial
    implementation uses an equal-weight average.

    This weighting should be revisited once real sessions are
    evaluated.
    """

    values = [
        category_scores.quantitative,
        category_scores.argumentation,
        category_scores.rebuttal,
        category_scores.structure,
        category_scores.persuasion,
        category_scores.logic,
    ]

    if not values:
        return 0.0

    return round(
        sum(values) / len(values),
        2,
    )


def build_coaching_scores(
    feedback: List[FeedbackItem],
) -> CoachingScores:
    """
    Build the complete CoachingScores object.
    """

    category_scores = calculate_category_scores(feedback)

    overall = calculate_overall_score(category_scores)

    return CoachingScores(
        categories=category_scores,
        overall=overall,
    )