from typing import Dict, List

from ..models.feedback import FeedbackItem
from ..models.scores import CategoryScores, CoachingScores


SEVERITY_PRIORITY = {
    "high": 4,
    "medium": 3,
    "low": 2,
    "positive": 1,
}


# ============================================================
# SCORING MODEL
#
# The previous formula was additive on raw counts:
#
#     50 + positive*15 - high*20 - medium*10 - low*5
#
# which saturates. A category that produced four positive
# observations scored 110 and clamped to 100; a category that
# produced three high-severity issues scored -10 and clamped to
# 0. On a real session that meant every qualitative category
# read 100 and delivery read 0, regardless of the speech.
#
# This version works on ratios instead of counts, so the number
# of observations a module happens to emit does not move the
# score on its own. Only the mix of observations does.
#
# A category with nothing but positive observations lands at
# POSITIVE_CEILING rather than 100. A perfect score is not
# something a coaching tool should hand out, and leaving
# headroom keeps the number honest.
# ============================================================

NEUTRAL_BASE = 50.0
POSITIVE_WEIGHT = 35.0
PENALTY_WEIGHT = 55.0

POSITIVE_CEILING = NEUTRAL_BASE + POSITIVE_WEIGHT

# How much each issue severity counts against the category,
# relative to one high-severity issue.
SEVERITY_PENALTY = {
    "high": 1.0,
    "medium": 0.6,
    "low": 0.3,
}

SCORED_CATEGORIES = (
    "quantitative",
    "argumentation",
    "rebuttal",
    "structure",
    "persuasion",
    "logic",
)


def aggregate_feedback(
    feedback: List[FeedbackItem],
) -> List[FeedbackItem]:
    """
    Combine feedback from all coaching modules.

    The aggregator:
        - removes exact duplicate feedback
        - prioritizes important issues
        - keeps positive feedback
        - returns feedback ordered by severity

    Args:
        feedback:
            Feedback generated by the coaching modules.

    Returns:
        A cleaned and prioritized list of FeedbackItem objects.
    """

    unique_feedback: List[FeedbackItem] = []
    seen = set()

    for item in feedback:
        key = (
            item.category,
            item.title,
            item.issue,
        )

        if key in seen:
            continue

        seen.add(key)
        unique_feedback.append(item)

    unique_feedback.sort(
        key=lambda item: SEVERITY_PRIORITY.get(
            item.severity,
            0,
        ),
        reverse=True,
    )

    return unique_feedback


def calculate_category_scores(
    feedback: List[FeedbackItem],
) -> CategoryScores:
    """
    Calculate category scores from feedback.

    A category with no observations scores NEUTRAL_BASE rather
    than zero. Absence of feedback is absence of signal, not
    evidence of a bad performance, and scoring it as zero
    dragged the overall score down whenever a module had
    nothing to say.

    Returns:
        CategoryScores containing scores from 0 to 100.
    """

    buckets: Dict[str, List[FeedbackItem]] = {
        category: []
        for category in SCORED_CATEGORIES
    }

    for item in feedback:
        if item.category in buckets:
            buckets[item.category].append(item)

    scores: Dict[str, float] = {}

    for category, items in buckets.items():

        if not items:
            scores[category] = NEUTRAL_BASE
            continue

        total = len(items)

        positives = sum(
            1
            for item in items
            if item.severity == "positive"
        )

        penalty = sum(
            SEVERITY_PENALTY.get(item.severity, 0.0)
            for item in items
        )

        score = (
            NEUTRAL_BASE
            + POSITIVE_WEIGHT * (positives / total)
            - PENALTY_WEIGHT * (penalty / total)
        )

        scores[category] = round(
            max(0.0, min(POSITIVE_CEILING, score)),
            1,
        )

    return CategoryScores(
        quantitative=scores["quantitative"],
        argumentation=scores["argumentation"],
        rebuttal=scores["rebuttal"],
        structure=scores["structure"],
        persuasion=scores["persuasion"],
        logic=scores["logic"],
    )


def calculate_overall_score(
    category_scores: CategoryScores,
) -> float:
    """
    Calculate the overall coaching score.

    Equal weight across the six categories. Revisit the
    weighting once there are enough real sessions to know which
    categories actually predict a better speech.
    """

    values = [
        category_scores.quantitative,
        category_scores.argumentation,
        category_scores.rebuttal,
        category_scores.structure,
        category_scores.persuasion,
        category_scores.logic,
    ]

    if not values:
        return 0.0

    return round(
        sum(values) / len(values),
        1,
    )


def build_coaching_scores(
    feedback: List[FeedbackItem],
) -> CoachingScores:
    """
    Build the complete CoachingScores object.
    """

    category_scores = calculate_category_scores(feedback)

    overall = calculate_overall_score(category_scores)

    return CoachingScores(
        categories=category_scores,
        overall=overall,
    )
